
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "accountsearch.fullname" . }}
  labels:
    {{- include "accountsearch.labels" . | nindent 4 }}
data:
  solr_url:  {{ .Values.solr.url }}
  solr_user: {{ .Values.solr.username }}
  solr_pwd:  {{ .Values.solr.pwd }}
