
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "accountsearch.fullname" . }}
  labels:
    {{- include "accountsearch.labels" . | nindent 4 }}
data:
  solr_url:  'http://host.docker.internal:8983/solr/accounts'
  solr_user:  'admin'
  solr_pwd:  '5qfOrZpA7u'
